### ISSUE TITLE
[Enhancement] Add "Help" section

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/Datalya#4]
### Enhancement

Add a "Help" section:

- [x] How to add and configure Blocks
- [x] How to add an item
- [x] How to edit an item
- [x] How to save a database
- [x] How to create a database

### Other informations

These informations will be available in the "Help" window.
